#!/bin/bash

# Fuzzy selection for notes stored locally on this machine, using fzf.
# Michael Fincham <michael@hotplate.co.nz> 2020-11-16

main() {
  previous_file="$1"
  file_to_edit=$(select_file "$previous_file")

  if [ -n "$file_to_edit" ]; then
    vim "$file_to_edit"
    main "$file_to_edit"
  fi
}

select_file() {
    given_file="$1"
    output=$(fzf --preview="pygmentize -g {}" --preview-window=right:80%:wrap --print-query --query="$given_file")
    if [ $? -eq 1 ] ; then
        echo "$output"
    else
        echo "$output" | tail -n 1
    fi
}

cd ~/Notes || exit 1
main ""
