#!/bin/bash

# Adapted from https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu to use rofi.
# Should be safe against all the various ways for this to go wrong.
# Michael Fincham <michael@hotplate.co.nz> & others 2020-11-16

shopt -s nullglob globstar

typeit=1

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | rofi -monitor -2 -dmenu -p "password" -f -i "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	gopass show -c "$password" 2>/dev/null
else
	gopass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
		xdotool type --clearmodifiers --file -
        notify-send "Typed password for '$password'"
fi

